In [5]:
#unit 2
#pre processing
#mean removel
import numpy as np
from sklearn import preprocessing

data=np.array([[2],[4],[6],[8],[10]])

mean=data.mean(axis=0)
mean_removed=data-mean
print(mean_removed)
print(mean_removed.std(axis=0))
print(mean_removed.mean(axis=0))
data_standardize=preprocessing.scale(data)
print(data_standardize)
print(data_standardize.mean(axis=0))

[[-4.]
 [-2.]
 [ 0.]
 [ 2.]
 [ 4.]]
[2.82842712]
[0.]
[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]
[0.]


In [6]:
#scaling
import numpy as np
from sklearn import preprocessing

data=np.array([[10],[20],[30],[40],[50]])
print(data)
print('*'*50)
data_scaler=preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_data=data_scaler.fit_transform(data)
print(scaled_data)

[[10]
 [20]
 [30]
 [40]
 [50]]
**************************************************
[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


In [10]:
#normlization
import numpy as np
from sklearn import preprocessing

#dataset (will take 2 columns per record)
data=np.array([[3,4],[1,2],[5,12]])
print(data)
print('*'*50)
#l1 normlization
normalise_l1=preprocessing.normalize(data,norm='l1')
print(normalise_l1)
print('*'*50)
#l2 normlization
normalise_l2=preprocessing.normalize(data,norm='l2')
print(normalise_l2)

[[ 3  4]
 [ 1  2]
 [ 5 12]]
**************************************************
[[0.42857143 0.57142857]
 [0.33333333 0.66666667]
 [0.29411765 0.70588235]]
**************************************************
[[0.6        0.8       ]
 [0.4472136  0.89442719]
 [0.38461538 0.92307692]]


In [12]:
#binarization
import numpy as np
from sklearn import preprocessing

data=np.array([[10.2],[11.2],[9.21],[20.3],[10]])
print(data)
print('*'*50)
binariz_data=preprocessing.Binarizer(threshold=10.2).transform(data)
print(binariz_data)

[[10.2 ]
 [11.2 ]
 [ 9.21]
 [20.3 ]
 [10.  ]]
**************************************************
[[0.]
 [1.]
 [0.]
 [1.]
 [0.]]


In [14]:
#label encoding
from sklearn import preprocessing
#data
labels=['mengo','banana','apple','grapes','apple','mango']
print(labels)
#encoding
label_encoder=preprocessing.LabelEncoder()
op=label_encoder.fit_transform(labels)
print('Encoded labels:',op)
#testing
test_labels=['mengo','banana']
print(label_encoder.transform(test_labels))
test_code=[3,1]
print(label_encoder.inverse_transform(test_code))

['mengo', 'banana', 'apple', 'grapes', 'apple', 'mango']
Encoded labels: [4 1 0 2 0 3]
[4 1]
['mango' 'banana']
